sudo: required
language: nix
os: osx

branches:
  only:
  - master
notifications:
  email:
  - false

script:
- nix-shell --pure --run 'echo done'
- nix-shell --pure --run 'pkg-config --list-all|sort'
- nix-build

